# Receita remota de exemplo — tmux
# Demonstra receita com múltiplas deps e provides.

name         = "tmux"
version      = "3.4"
description  = "Multiplexador de terminal"
homepage     = "https://tmux.github.io/"
license      = "ISC"
maintainer   = "Nicholas Marriott <nicholas.marriott@example.org>"
repository   = "local"
architecture = "any"

depends       = ["ncurses>=6.0", "libevent>=2.1"]
optional_deps = ["utempter"]

source        = "https://github.com/tmux/tmux/releases/download/3.4/tmux-3.4.tar.gz"
# sha256 = "preencha com: sha256sum tmux-3.4.tar.gz"

build_system   = "autotools"
configure_args = ["--enable-utempter"]
